<?php

namespace Database\Seeders;

use App\Models\OrderStatus;
use Illuminate\Database\Seeder;

class OrderStatusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        collect([
            [
                'name' => 'Menunggu Pemesanan',
                'code' => 'menunggu-pemesanan',
                'description' => 'Batch atau pesanan masih menunggu proses pemesanan.',
                'color' => '#64748b',
                'sequence' => 10,
                'status_type' => 'process',
                'scope' => 'batch',
                'is_initial' => true,
                'is_final' => false,
            ],
            [
                'name' => 'Sudah Dipesan',
                'code' => 'sudah-dipesan',
                'description' => 'Jajanan sudah dipesan ke supplier.',
                'color' => '#2563eb',
                'sequence' => 20,
                'status_type' => 'process',
                'scope' => 'all',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Dalam Perjalanan',
                'code' => 'dalam-perjalanan',
                'description' => 'Pesanan sedang dikirim menuju warehouse.',
                'color' => '#7c3aed',
                'sequence' => 30,
                'status_type' => 'process',
                'scope' => 'batch',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Tiba di Warehouse',
                'code' => 'tiba-di-warehouse',
                'description' => 'Pesanan sudah tiba dan menunggu proses sortir.',
                'color' => '#0891b2',
                'sequence' => 40,
                'status_type' => 'process',
                'scope' => 'batch',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Siap Dikirim',
                'code' => 'siap-dikirim',
                'description' => 'Pesanan sudah siap dikirim ke member.',
                'color' => '#0d9488',
                'sequence' => 50,
                'status_type' => 'process',
                'scope' => 'batch',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Selesai',
                'code' => 'selesai',
                'description' => 'Pesanan sudah selesai.',
                'color' => '#16a34a',
                'sequence' => 60,
                'status_type' => 'success',
                'scope' => 'all',
                'is_initial' => false,
                'is_final' => true,
            ],
            [
                'name' => 'Dibatalkan',
                'code' => 'dibatalkan',
                'description' => 'Pesanan dibatalkan.',
                'color' => '#dc2626',
                'sequence' => 70,
                'status_type' => 'cancelled',
                'scope' => 'all',
                'is_initial' => false,
                'is_final' => true,
            ],
            [
                'name' => 'Refund',
                'code' => 'refund',
                'description' => 'Pesanan member masuk proses refund.',
                'color' => '#ea580c',
                'sequence' => 80,
                'status_type' => 'failed',
                'scope' => 'member_order',
                'is_initial' => false,
                'is_final' => true,
            ],
            [
                'name' => 'Menunggu DP',
                'code' => 'menunggu-dp',
                'description' => 'Buyer belum menyelesaikan down payment untuk slot GO.',
                'color' => '#ca8a04',
                'sequence' => 85,
                'status_type' => 'process',
                'scope' => 'member_order',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Secured',
                'code' => 'secured',
                'description' => 'Slot atau item sudah berhasil diamankan dari seller.',
                'color' => '#2563eb',
                'sequence' => 86,
                'status_type' => 'process',
                'scope' => 'all',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'On Hand Korea',
                'code' => 'on-hand-korea',
                'description' => 'Item sudah diterima warehouse/proxy Korea.',
                'color' => '#7c3aed',
                'sequence' => 87,
                'status_type' => 'process',
                'scope' => 'batch',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'EMS Korea-ID',
                'code' => 'ems-korea-id',
                'description' => 'Paket sedang dikirim dari Korea ke Indonesia.',
                'color' => '#0891b2',
                'sequence' => 88,
                'status_type' => 'process',
                'scope' => 'batch',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Customs Clearance',
                'code' => 'customs-clearance',
                'description' => 'Paket sedang proses bea cukai.',
                'color' => '#db2777',
                'sequence' => 89,
                'status_type' => 'process',
                'scope' => 'batch',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Ready Pickup',
                'code' => 'ready-pickup',
                'description' => 'Merch sudah siap pickup atau dikirim ke buyer.',
                'color' => '#0d9488',
                'sequence' => 91,
                'status_type' => 'process',
                'scope' => 'all',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Menunggu Pelunasan',
                'code' => 'menunggu-pelunasan',
                'description' => 'Status khusus untuk pesanan member yang belum lunas.',
                'color' => '#ca8a04',
                'sequence' => 90,
                'status_type' => 'process',
                'scope' => 'member_order',
                'is_initial' => false,
                'is_final' => false,
            ],
            [
                'name' => 'Barang Kurang',
                'code' => 'barang-kurang',
                'description' => 'Status khusus item jika jumlah barang tidak lengkap.',
                'color' => '#be123c',
                'sequence' => 100,
                'status_type' => 'failed',
                'scope' => 'order_item',
                'is_initial' => false,
                'is_final' => false,
            ],
        ])->each(function (array $status): void {
            OrderStatus::updateOrCreate(
                ['code' => $status['code']],
                $status + ['is_active' => true],
            );
        });
    }
}
